# Generated by Django 5.2.6 on 2025-09-04 07:34

import collector.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('role', models.CharField(choices=[('employee', '員工'), ('visitor', '訪客')], default='employee', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(db_index=True, max_length=64)),
                ('image', models.ImageField(upload_to=collector.models.capture_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='collector.profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
