# Generated by Django 5.2.5 on 2025-09-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
