# Generated by Django 5.2.5 on 2025-09-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_profile_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='external_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
