# Generated by Django 5.2.6 on 2025-09-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_remove_profile_external_id_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='image_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='capture',
            name='image_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
